name: Dev.To IntegraÃ§Ã£o
on:
  schedule:
     - cron: '0 12 * * *'
  workflow_dispatch:
    inputs:
      colaborador:
        description: 'Seu nome'     
        required: true
        default: 'anonimo'
    
jobs:
  buscar-minhas-postagens:
    name: buscar-postagens
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/lucastmp"
          enable_keepalive: true
          commit_message: "Commit para re-load do action Dev.To"
          committer_username: "dev-to-bot"
          custom_tags: "categoryName/category/"
          date_format: "mm/dd/yyyy"
          template: "$counter $randomEmoji(ğŸ”¥,ğŸš€,ğŸ‘¨â€ğŸ’») [$title]($url) $categoryName | $date $newline"
          
          
