name: Dev.To IntegraÃ§Ã£o
on:
  schedule:
     - cron: '0 12 * * *'
  workflow_dispatch:
    inputs:
      colaborador:
        description: 'Seu nome'     
        required: true
        default: 'anonimo'
    
jobs:
  buscar-minhas-postagens:
    name: buscar-postagens
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/lucastmp"
          enable_keepalive: true
          commit_message: "Commit para re-load do action Dev.To"
          committer_username: "dev-to-bot"
          custom_tags: "principalTag/category/"
          date_format: "dd/mm/yyyy"
          retry_count: 6
          retry_wait_time: 10
          template: "$newline - $randomEmoji(ğŸ”¥,ğŸš€,ğŸ‘¨â€ğŸ’») <a href='$url'>$title</a> | ğŸ·ï¸ Tag: $principalTag | ğŸ“… Data: $date"
          
          
